# Generated by Django 6.0.5 on 2026-05-27 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('classic', 'Classic CV'), ('ai', 'AI Model')], max_length=10)),
                ('algorithm', models.CharField(max_length=20)),
                ('is_fake', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('metrics', models.JSONField(default=dict)),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('processing_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analysis.uploadedimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
